name: Reusable PR E2E KinD

on:
  workflow_call:
    inputs:
      image:
        description: Operator image reference to test.
        type: string
        required: true

jobs:
  e2e-kind:
    name: E2E KinD
    runs-on: gke-kind-e2e
    env:
      KIND_CLUSTER_NAME: scylla-operator-e2e
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install KinD
        run: |
          # Install the latest KinD release.
          go install sigs.k8s.io/kind@latest

      - name: Install yq
        run: |
          go install github.com/mikefarah/yq/v4@latest

      - name: Set up KinD cluster and deploy operator
        env:
          SO_IMAGE: ${{ inputs.image }}
        run: |
          make kind-setup

      - name: Run KinD E2E tests
        env:
          CLUSTER_NAME: ${{ env.KIND_CLUSTER_NAME }}
        run: |
          ./hack/kind/run-e2e-tests.sh
